/**:
  ros__parameters:
    hw_platform: "laptop"
    use_axis_camera: false

controller:
  ros__parameters:
    # UPDATED: Matches your Espressif device
    serial_port: "/dev/ttyACM0"
    baudrate: 115200
    base_frame: "base_link"
    odom_frame: "odom"
    publish_tf: true
    robot_type: "lizard"
    use_lizard: true
    read_data:
      list:
        - "v_batt"
        - "motor_status"
      v_batt:
        default: 0.0
        type: "double"
      motor_status:
        default: 0
        type: "int"

ublox_gps_node:
  ros__parameters:
    # UPDATED: Matches your u-blox device
    device: "/dev/ttyACM1"
    frame_id: "gps"
    baudrate: 460800
    uart1:
      baudrate: 460800
    meas: 5
    dgnss_mode: 3
    inf:
      all: true
    publish:
      all: true
      nav:
        pvt: true
        sat: true
    gnss:
      gps: true
      glonass: true
      beidou: true
      galileo: true

web_ui:
  ros__parameters:
    host: "0.0.0.0"
    port: 8080

tf_base_link_imu:
  ros__parameters:
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0, 1.0]

tf_imu_gnss:
  ros__parameters:
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0, 1.0]

tf_imu_vsm:
  ros__parameters:
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0, 1.0]
