basekit_driver_node:
  ros__parameters:
     # port: "/dev/ttyACM0"
    baudrate: 115200
    read_data:
      list: ["v_batt", "current", "temp"]
      v_batt:
        type: "float"
        default: 0.0
        unit: "V"
      current:
        type: "float"
        default: 0.0
        unit: "A"
      temp:
        type: "float"
        default: 0.0
        unit: "C"
