basekit_driver_node:
  ros__parameters:
     # port: "/dev/ttyACM0"
    baudrate: 115200
    update_rate: 10
    read_data:
      list: ["v_batt", "motor_status", "encoders"]
      v_batt:
        type: "Float32"
        default: 0.0
      motor_status:
        type: "String"
        default: "unknown"
      encoders:
        type: "Int32MultiArray"
        default: [0, 0]
